latestVersion:
  prevalence_estimates:
    names:
    - - analysis_id
      - n_persons
      - person_days
      - n_events
      - incidence_start_date
      - incidence_end_date
      - person_years
      - incidence_100000_pys
      - incidence_100000_pys_95CI_lower
      - incidence_100000_pys_95CI_upper
      - cohort_obscured
      - result_obscured
      - outcome_cohort_id
      - outcome_cohort_name
      - analysis_outcome_washout
      - analysis_repeated_events
      - analysis_interval
      - analysis_complete_database_intervals
      - denominator_cohort_id
      - analysis_min_cell_count
      - denominator_cohort_name
      - denominator_age_group
      - denominator_sex
      - denominator_days_prior_history
      - denominator_start_date
      - denominator_end_date
      - denominator_strata_cohort_definition_id
      - denominator_strata_cohort_name
      - denominator_closed_cohort
      - cdm_name
      - database_name
  incidence_estimates:
    names:
    - analysis_id
    - n_persons
    - person_days
    - n_events
    - incidence_start_date
    - incidence_end_date
    - person_years
    - incidence_100000_pys
    - incidence_100000_pys_95CI_lower
    - incidence_100000_pys_95CI_upper
    - cohort_obscured
    - result_obscured
    - outcome_cohort_id
    - outcome_cohort_name
    - analysis_outcome_washout
    - analysis_repeated_events
    - analysis_interval
    - analysis_complete_database_intervals
    - denominator_cohort_id
    - analysis_min_cell_count
    - denominator_cohort_name
    - denominator_age_group
    - denominator_sex
    - denominator_days_prior_history
    - denominator_start_date
    - denominator_end_date
    - denominator_strata_cohort_definition_id
    - denominator_strata_cohort_name
    - denominator_closed_cohort
    - cdm_name
    - database_name
  prevalence_attrition:
    names:
    - analysis_id
    - number_records
    - number_subjects
    - reason_id
    - reason
    - excluded_records
    - excluded_subjects
    - outcome_cohort_id
    - outcome_cohort_name
    - analysis_outcome_washout
    - analysis_repeated_events
    - analysis_interval
    - analysis_complete_database_intervals
    - denominator_cohort_id
    - analysis_min_cell_count
    - denominator_cohort_name
    - denominator_age_group
    - denominator_sex
    - denominator_days_prior_history
    - denominator_start_date
    - denominator_end_date
    - denominator_strata_cohort_definition_id
    - denominator_strata_cohort_name
    - denominator_closed_cohort
    - cdm_name
    - database_name
  incidence_attrition:
    names:
    - analysis_id
    - number_records
    - number_subjects
    - reason_id
    - reason
    - excluded_records
    - excluded_subjects
    - outcome_cohort_id
    - outcome_cohort_name
    - analysis_outcome_washout
    - analysis_repeated_events
    - analysis_interval
    - analysis_complete_database_intervals
    - denominator_cohort_id
    - analysis_min_cell_count
    - denominator_cohort_name
    - denominator_age_group
    - denominator_sex
    - denominator_days_prior_history
    - denominator_start_date
    - denominator_end_date
    - denominator_strata_cohort_definition_id
    - denominator_strata_cohort_name
    - denominator_closed_cohort
    - cdm_name
    - database_name
