IncidencePrevalence:
  incidence_estimates:
    names:
    - incidence_start_date
    - incidence_end_date
    - incidence_100000_pys
    - incidence_100000_pys_95CI_lower
    - incidence_100000_pys_95CI_upper
  prevalence_estimates:
    names:
    - prevalence_start_date
    - prevalence_end_date
    - prevalence
    - prevalence_95CI_lower
    - prevalence_95CI_upper
  incidence_attrition:
    names:
    - number_records
    - number_subjects
    - reason_id
    - reason
    - excluded_records
    - excluded_subjects
  prevalence_attrition:
    names:
    - number_records
    - number_subjects
    - reason_id
    - reason
    - excluded_records
    - excluded_subjects
TreatmentPatterns:
  treatmentPathways:
    names:
    - path
    - freq
    - sex
    - age
    - indexYear
PatientProfiles:
  summarised_characteristics:
    names:
    - cdm_name
    - result_type
    - group_name
    - group_level
    - strata_name
    - strata_level
    - variable
    - variable_level
    - variable_type
    - estimate_type
    - estimate
  Summarised Large Scale Characteristics:
    names:
    - result_type
    - cdm_name
    - group_name
    - group_level
    - strata_name
    - strata_level
    - table_name
    - type
    - analysis
    - concept
    - variable
    - variable_level
    - estimate_type
    - estimate
CohortSurvival:
  Survival estimate:
    names:
    - cdm_name
    - result_type
    - group_name
    - group_level
    - strata_name
    - strata_level
    - variable
    - variable_level
    - variable_type
    - estimate_type
    - time
    - analysis_type
    - outcome
    - estimate
  Survival cumulative incidence:
    names:
    - cdm_name
    - result_type
    - group_name
    - group_level
    - strata_name
    - strata_level
    - variable
    - variable_level
    - variable_type
    - estimate_type
    - time
    - analysis_type
    - outcome
    - estimate
